      name: Execução de testes regressivos

      on:
        push:
          branches: [ "master" ]
        pull_request:
          branches: [ "master" ]
        schedule:
          - cron: '0 9 * * 1-5'

      jobs:
        build:

          runs-on: ubuntu-latest


          steps:

            - uses: actions/checkout@v3
            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                java-version: '11'
                distribution: 'temurin'
                cache: maven
            - name: Build with Maven
              run: mvn -B package --file pom.xml -DskipTests

            - name: Docker Login
              uses: docker/login-action@v2.1.0
              with:
                username: ${{ secrets.USER_DOCKER }}
                password: ${{ secrets.PASSWORD_DOCKER }}

#            - name: Build and Push Docker images
#              uses: docker/build-push-action@v3.2.0
#              with:
#                cotext: .
#                push: true
#                tags: |
#                  rodrigolimaads/api-simulacao:1.0

            - name: Start containers
              run: docker-compose -f "docker-compose.yml" up -d --build && sleep 10

            - name: Run tests
              run:  mvn test -Dgroups="regressivo"

            - name: Stop containers
              if: always()
              run: docker-compose -f "docker-compose.yml" down
